// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgJNiErCGP2ldNA6-luCEVMX4qvXKwweQ',
    appId: '1:364156883260:web:b0089c1fc9c5e4055e4e39',
    messagingSenderId: '364156883260',
    projectId: 'foodit-d09f1',
    authDomain: 'foodit-d09f1.firebaseapp.com',
    storageBucket: 'foodit-d09f1.appspot.com',
    measurementId: 'G-ZN60GGT4Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqaTYh0YPCRGb2kjXzPRFWlw5fUicEMWw',
    appId: '1:364156883260:android:43c5a23ca716779b5e4e39',
    messagingSenderId: '364156883260',
    projectId: 'foodit-d09f1',
    storageBucket: 'foodit-d09f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBF_ID1BlifYaa29pvwy26wDs7J7oer6s',
    appId: '1:364156883260:ios:2046f3456b374f9a5e4e39',
    messagingSenderId: '364156883260',
    projectId: 'foodit-d09f1',
    storageBucket: 'foodit-d09f1.appspot.com',
    iosBundleId: 'com.example.foodIt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBF_ID1BlifYaa29pvwy26wDs7J7oer6s',
    appId: '1:364156883260:ios:2046f3456b374f9a5e4e39',
    messagingSenderId: '364156883260',
    projectId: 'foodit-d09f1',
    storageBucket: 'foodit-d09f1.appspot.com',
    iosBundleId: 'com.example.foodIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgJNiErCGP2ldNA6-luCEVMX4qvXKwweQ',
    appId: '1:364156883260:web:1fffaa4561dc58775e4e39',
    messagingSenderId: '364156883260',
    projectId: 'foodit-d09f1',
    authDomain: 'foodit-d09f1.firebaseapp.com',
    storageBucket: 'foodit-d09f1.appspot.com',
    measurementId: 'G-RKP7JH1Q8F',
  );

}